### ISSUE TITLE
Recent update of FF for Android to 79.0.5 - PfP "not yet available"

### ISSUE THREAD

**Issue by PresGas** [palant/pfp#117] opened 2020-08-28 00:42 UTC
PfP was working for me until today when FF auto updated. Any plans to get it available? I had used it on older FF Android versions and it really helped across my devices. Everything worked flawlessly.

**Comment by palant** [comment] 2020-08-28 05:24
I just checked and PfP is of course marked as compatible with the latest FF/Android version. I looked through https://blog.mozilla.org/blog/2020/08/25/introducing-a-new-firefox-for-android-experience/ and I don't see why Firefox Daylight would disable any add-ons. Will have to look into this. :disappointed:

**Comment by PresGas** [comment] 2020-08-28 12:17
Thanks so much! I did recall looking at the preview of what was going to become this version of FF and noted PfP was disabled, but thought you were aware. Should have still reported it; that's how the community works!
If there is a way to manually enable it or a beta channel for a fix, feel free to let me know and I will be happy to test!

**Comment by palant** [comment] 2020-08-28 12:49
Just great: https://blog.mozilla.org/addons/2019/10/23/fx-preview-geckoview-add-ons-support/

So the way I read this: Firefox Preview has been built from scratch to replace Firefox for Android. It's now live on the release channel as Firefox Daylight. That new browser has very limited support for browser extensions so far, and PfP happens to be unsupported. I'm unsure whether that assessment is based on some APIs used by PfP or whether they simply enable “compatible” add-ons manually.

Of course, no information has been sent out to extension developers. Because extension developers have to keep track of that proactively. And it's such a minor change anyway…

**Comment by PresGas** [comment] 2020-08-28 13:00
All the more reason I feel semi-responsible NOT making an issue when I saw that article and played around with FF Preview.
:cry: 

Would this also be the time to just get it pushed to the Recommended Extensions?
https://support.mozilla.org/en-US/kb/recommended-extensions-program
They don't have to be dependent on each other but perhaps that could help having multiple "hooks" into them. I am surprised by some of the addons that ARE there, but also you have the security CV via your blog so it should be pretty smooth getting it there.

Like I said earlier. I'd be happy to test out anything with what I have.

**Comment by palant** [comment] 2020-08-28 13:07
Don't worry, with only a handful of extensions in that program PfP wouldn't have a chance anyway. Mozilla essentially killed add-on support, saved for a bunch of hand-selected ones.

I'm currently trying out whether the extension actually runs on the new browser. Given the other extensions which do, I suspect that PfP will work just fine – it's a policy decision, not a technical one.

**Comment by palant** [comment] 2020-08-28 13:19
Confirmed that – PfP seems to work perfectly fine when installed (as a temporary extension, in debugging mode via adb). It even still has its data. But the browser doesn't allow it to run.

Resolving as “invalid” which really means “nothing I can do about this”. :disappointed:

**Closed by palant** 2020-08-28 13:19 UTC
Labels: invalid

**Comment by PresGas** [comment] 2020-08-28 16:02
Adding this here as another data point. Not sure there is nothing an add-on dev can do.
https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/

Yes, this is a bad vector for Mozilla; but that does not mean we simply throw our hands in the air.

**Comment by PresGas** [comment] 2020-08-29 16:06
One final piece of clarity for me (and others that may be using this on FF), @palant . I know I picked PfP as my manager on all may devices because of your articles and the ability to use it on all my devices.

Does this mean you are considering this not fixable? If so, does that mean that we either wait for Mozilla to add it or that the PfP project is officially dropping support for Android FF? 

Is there a way forward that users of PfP can do to help you out in this?

I have attempted a "local install" of your [current release](https://github.com/palant/pfp/releases/tag/2.2.4) but I am having some issues that would be a separate ticket and not applicable here.

Again, thanks so much for putting this out and doing your blog.

**Comment by palant** [comment] 2020-08-29 16:30
Yes, I strongly suspect that the add-ons platform on Android is dead. I have little hope that Mozilla will reopen it again, and if they don't they certainly won't bother will niche add-ons like PfP.

“Local install” is currently the only possible solution. And I should finally bundle it in an Android app (#91).
